# Generated by Django 3.2.9 on 2021-11-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blogengine', '0001_initial'), ('blogengine', '0002_alter_blogarticle_publish_status'), ('blogengine', '0003_auto_20211118_1133'), ('blogengine', '0004_blogarticle_thumbnail_upload'), ('blogengine', '0005_alter_blogarticle_thumbnail_upload'), ('blogengine', '0006_alter_blogarticle_thumbnail_upload'), ('blogengine', '0007_auto_20211120_0724'), ('blogengine', '0008_alter_blogarticle_seo_url')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('preview', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(default=None)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('publish_status', models.CharField(choices=[('DR', 'Draft'), ('PB', 'Publihsed'), ('UL', 'Unlisted')], default='DR', max_length=2)),
                ('thumbnail_upload', models.ImageField(null=True, upload_to='blog_thumbs/')),
                ('seo_url', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
