# Generated by Django 3.2.9 on 2021-11-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=200)),
                ('preview', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(default=None)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('publish_status', models.IntegerField(choices=[('0', 'Draft'), ('1', 'Publihsed'), ('2', 'Unlisted')], default='0')),
            ],
        ),
    ]
