# Generated by Django 3.2.9 on 2021-11-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0001_squashed_0008_alter_blogarticle_seo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='thumbnail_upload',
            field=models.ImageField(blank=True, null=True, upload_to='blog_thumbs/'),
        ),
    ]
