# Generated by Django 3.2.9 on 2021-11-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='publish_status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'Publihsed'), ('UL', 'Unlisted')], default='DR', max_length=2),
        ),
    ]
