# Generated by Django 3.2.9 on 2021-12-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0002_alter_blogarticle_thumbnail_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='tag',
            field=models.ManyToManyField(to='blogengine.BlogTag'),
        ),
    ]
