# Generated by Django 3.2.9 on 2021-11-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0003_auto_20211118_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='thumbnail_upload',
            field=models.ImageField(null=True, upload_to='file_uploads/'),
        ),
    ]
