# Generated by Django 3.2.9 on 2021-11-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0004_blogarticle_thumbnail_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='thumbnail_upload',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
