# Generated by Django 3.2.9 on 2021-12-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0005_auto_20211212_0038'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogtag',
            index=models.Index(fields=['url_slug'], name='index__url_slug'),
        ),
    ]
