# Generated by Django 3.2.9 on 2021-12-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0006_blogtag_index__url_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blogtag',
            name='index__url_slug',
        ),
    ]
