# Generated by Django 3.2.9 on 2021-11-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0007_auto_20211120_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='seo_url',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
